from src.services.media.lanes import CODE_LANE_MEDIA as CODE_LANE_MEDIA
from src.services.media.lanes import PASSWORD_PROTECTED_TEXT as PASSWORD_PROTECTED_TEXT
from src.services.media.lanes import canonical_suffix as canonical_suffix
from src.services.media.lanes import code_lane_refusal as code_lane_refusal
from src.services.media.lanes import is_code_lane as is_code_lane
from src.services.media.lanes import is_opc_archive as is_opc_archive
from src.services.media.lanes import looks_password_protected as looks_password_protected
from src.services.media.lanes import pdf_looks_password_protected as pdf_looks_password_protected
from src.services.media.lanes import pdf_looks_truncated as pdf_looks_truncated
from src.services.media.lanes import pdf_refusal as pdf_refusal
from src.services.media.magic import ALLOWED_MEDIA as ALLOWED_MEDIA
from src.services.media.magic import bytes_match_declared as bytes_match_declared
from src.services.media.magic import chip_kind_for as chip_kind_for
from src.services.media.magic import magic_matches as magic_matches
