"""The 0034 migration's three round-3 fixes, none of which had a regression test.

`--autogenerate` drift, the two partial collapse indexes, and the `lock_timeout` guard all
landed on #147 without anything pinning them: deleting the `__table_args__` declarations in
`deployment.py` and `project.py` left 164 tests green. The drift in particular was found by
running `alembic revision --autogenerate` BY HAND during review, and nothing stopped it
recurring (#147 round 3 review).

The autogenerate check is the sharp one. A raw-SQL index in a migration that the ORM does not
also declare is invisible to `Base.metadata`, so the next `--autogenerate` emits a `drop_index`
for it — a migration that silently deletes the marketplace's indexes, authored by a tool, in a
PR about something else entirely.
"""

from __future__ import annotations

import pathlib

import sqlalchemy as sa
from alembic.autogenerate import compare_metadata
from alembic.migration import MigrationContext

from src.db.base import Base

_INDEXDEF_SQL = sa.text("SELECT indexname, indexdef FROM pg_indexes WHERE indexname = ANY(:names)")
MIGRATION_PATH = (
    pathlib.Path(__file__).resolve().parents[2]
    / "alembic"
    / "versions"
    / "2026_08_24_0034_project_description_fts.py"
)

_COLLAPSE_INDEXES = {
    "ix_deployments_success_collapse",
    "ix_deployments_unpublished_collapse",
}
_FTS_INDEX = "ix_projects_description_tsv"


async def test_autogenerate_against_the_migrated_schema_is_empty(test_engine) -> None:
    """The check that would have caught round 2's drift, run automatically this time.

    An empty diff means every index the migrations created is also declared on the ORM
    models, so `alembic revision --autogenerate` has nothing to say. A non-empty diff is
    printed in full rather than summarised: the useful part is WHICH object drifted, and a
    bare `assert not diffs` sends the reader back to reproduce it by hand.
    """

    def _compare(sync_conn: sa.Connection) -> list[object]:
        # `run_sync` hands the SYNC Connection the greenlet is driving, which is exactly what
        # MigrationContext wants — alembic has no async API of its own.
        context = MigrationContext.configure(sync_conn)
        return compare_metadata(context, Base.metadata)

    async with test_engine.connect() as conn:
        diffs = await conn.run_sync(_compare)

    assert diffs == [], (
        "alembic --autogenerate wants to change the schema, so the ORM models and the "
        f"migrations disagree. A `remove_index` here means a migration created an index no "
        f"model declares, and the next autogenerated revision will DROP it. Diff: {diffs}"
    )


async def test_the_collapse_indexes_exist_with_their_partial_predicates(db_session) -> None:
    """Both marketplace indexes exist, and both are PARTIAL.

    The predicate is the whole point: a plain `(app_id, id DESC)` index would satisfy a
    naive "does the index exist" check while indexing every historical deploy attempt
    instead of the small live subset, so the predicate is asserted, not just the name.
    """
    rows = (
        await db_session.execute(
            _INDEXDEF_SQL,
            {"names": list(_COLLAPSE_INDEXES | {_FTS_INDEX})},
        )
    ).all()
    by_name = {name: definition for name, definition in rows}

    assert _COLLAPSE_INDEXES <= by_name.keys(), (
        f"missing collapse index(es): {_COLLAPSE_INDEXES - by_name.keys()}"
    )
    success_def = by_name["ix_deployments_success_collapse"]
    # BOTH halves of the predicate, asserted separately. An index missing the
    # `url IS NOT NULL` clause would index rows the query can never use while still
    # satisfying a status-only check. (An earlier version of this `or`-ed a strict form
    # with a loose one, which made the strict half dead weight.)
    assert "status = 'succeeded'" in success_def, success_def
    assert "url IS NOT NULL" in success_def, success_def
    assert "unpublished_at IS NOT NULL" in by_name["ix_deployments_unpublished_collapse"]
    # The FTS index is GIN, not the btree a default would produce.
    assert "USING gin" in by_name[_FTS_INDEX]


def test_both_halves_of_the_migration_reset_lock_timeout() -> None:
    """`SET LOCAL lock_timeout` must be handed back in BOTH `upgrade()` and `downgrade()`.

    THIS IS A SOURCE-LEVEL ASSERTION, and deliberately so. An earlier version connected to
    the migrated database and asserted `SHOW lock_timeout` was `0` — which passed with the
    reset DELETED, because `SET LOCAL` is scoped to the TRANSACTION that set it and every
    test here gets a fresh connection. It could not observe the failure it claimed to pin.

    The real leak is intra-transaction: `alembic/env.py` leaves `transaction_per_migration`
    at False, so one `alembic upgrade` runs every pending revision in a SINGLE transaction
    and an unreset `SET LOCAL` applies to all of them. A later revision that legitimately
    waits more than 5s on a lock would then abort with `lock_not_available` and roll back
    the whole upgrade. Reproducing that needs a multi-revision upgrade staged one revision
    back, which is `test_migration_downgrade.py`'s territory rather than a unit test's.

    So this pins what actually regresses: someone deleting the reset. It fails the moment
    either half loses it, which the behavioural version did not.
    """
    source = MIGRATION_PATH.read_text(encoding="utf-8")
    upgrade_src = source[source.index("def upgrade()") : source.index("def downgrade()")]
    downgrade_src = source[source.index("def downgrade()") :]

    for name, body in (("upgrade", upgrade_src), ("downgrade", downgrade_src)):
        assert "SET LOCAL lock_timeout = '5s'" in body, (
            f"{name}() no longer sets a lock_timeout, so its ACCESS EXCLUSIVE DDL can queue "
            "behind an open reader and block every request for that table"
        )
        assert "SET LOCAL lock_timeout = DEFAULT" in body, (
            f"{name}() no longer RESETS lock_timeout. `transaction_per_migration` is False, "
            "so this leaks into every later revision in the same `alembic upgrade`"
        )
        assert body.index("SET LOCAL lock_timeout = '5s'") < body.index(
            "SET LOCAL lock_timeout = DEFAULT"
        ), f"{name}() resets lock_timeout before its DDL, so the guard covers nothing"
