"""worker_passes — the platform's own pulse (U11, R20)

Revision ID: 0027_worker_passes
Revises: 0026_deployment_classification

A pass record has to outlive everything the worker depends on, which is why it is a TABLE and not
a Redis key: under any eviction policy a Redis marker is evictable, so the staleness alarm would
fire spuriously AND its absence would be indistinguishable from a real outage — and absence is the
only signal that can detect a crashlooping worker.

The autogenerated draft also proposed dropping `ix_app_registry_project_id`, which is pre-existing
drift unrelated to this change. Removed: a migration that quietly drops somebody else's index is
how an unrelated regression ships inside a reviewed change.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0027_worker_passes"
down_revision: Union[str, Sequence[str], None] = "0026_deployment_classification"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "worker_passes",
        sa.Column("task_name", sa.String(length=128), nullable=False),
        sa.Column(
            "outcome",
            sa.Enum("OK", "DECLINED", "FAILED", name="worker_pass_outcome"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("counts", sa.JSON(), nullable=False),
        sa.Column("detail", sa.String(length=512), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_worker_passes_finished_at"), "worker_passes", ["finished_at"], unique=False
    )
    op.create_index(
        op.f("ix_worker_passes_task_name"), "worker_passes", ["task_name"], unique=False
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_worker_passes_task_name"), table_name="worker_passes")
    op.drop_index(op.f("ix_worker_passes_finished_at"), table_name="worker_passes")
    op.drop_table("worker_passes")
    sa.Enum(name="worker_pass_outcome").drop(op.get_bind(), checkfirst=True)
