"""worker_passes — the platform's own pulse (U11, R20)

Revision ID: 0027_worker_passes
Revises: 0026_deployment_classification

A pass record has to outlive everything the worker depends on, which is why it is a TABLE and not
a Redis key: under any eviction policy a Redis marker is evictable, so the staleness alarm would
fire spuriously AND its absence would be indistinguishable from a real outage — and absence is the
only signal that can detect a crashlooping worker.

The autogenerated draft also proposed dropping `ix_app_registry_project_id`, which is pre-existing
drift unrelated to this change. Removed: a migration that quietly drops somebody else's index is
how an unrelated regression ships inside a reviewed change.

Two things the draft got wrong and this file now states outright. The enum literals were the
member NAMES (`OK`/`DECLINED`/`FAILED`) rather than the values every other enum in this schema
stores, and `PassOutcome` is a `StrEnum` — so the mismatch is invisible from Python and surfaces
only when somebody queries `WHERE outcome = 'failed'` and gets nothing. And `counts` was `sa.JSON`,
which renders as `json` on Postgres: text, re-parsed per read, un-indexable, no containment
operators. Both corrected here rather than in a follow-up, because this revision has never left
the branch.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0027_worker_passes"
down_revision: str | Sequence[str] | None = "0026_deployment_classification"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# The native worker_pass_outcome enum (ADR-0008), spelled in VALUES like every other enum here.
# create_type=False so THIS migration owns the lifecycle: explicit .create() in upgrade, .drop()
# in downgrade.
worker_pass_outcome = postgresql.ENUM(
    "ok",
    "declined",
    "failed",
    name="worker_pass_outcome",
    create_type=False,
)


def upgrade() -> None:
    worker_pass_outcome.create(op.get_bind(), checkfirst=True)
    op.create_table(
        "worker_passes",
        sa.Column("task_name", sa.String(length=128), nullable=False),
        sa.Column("outcome", worker_pass_outcome, nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("counts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("detail", sa.String(length=512), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_worker_passes_finished_at"), "worker_passes", ["finished_at"], unique=False
    )
    op.create_index(
        op.f("ix_worker_passes_task_name"), "worker_passes", ["task_name"], unique=False
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_worker_passes_task_name"), table_name="worker_passes")
    op.drop_index(op.f("ix_worker_passes_finished_at"), table_name="worker_passes")
    op.drop_table("worker_passes")
    worker_pass_outcome.drop(op.get_bind(), checkfirst=True)
